WITH STREAK AS (
    SELECT  DATE_TRUNC('WEEK', DATE) AS WEEK_START,
            PERSON_ID,
            COUNT(*) AS DAY_COUNT
    FROM read_csv('datasets/github_streak.csv')
    WHERE YEAR(DATE) = 2023
    GROUP BY DATE_TRUNC('WEEK', DATE), PERSON_ID
    HAVING DAY_COUNT >= 3
)

SELECT PERSON_ID, 
       COUNT(*) AS WEEK_COUNT
FROM STREAK
GROUP BY PERSON_ID 
HAVING WEEK_COUNT >= 20
ORDER BY WEEK_COUNT DESC;